### ISSUE TITLE
Generate the video - still has issues

### ISSUE THREAD

**Issue by Mr-Fen** [raspberrypilearning/push-button-stop-motion#14]
>>> avconv -r **10** -i /home/pi/animation/frame%03d.jpg -qscale 2 animation.mp4
SyntaxError: invalid syntax

doesnt like the space between the -r and 10

>>> avconv -r10 -i /home/pi/animation/frame%**03**d.jpg -qscale 2 animation.mp4
SyntaxError: invalid token

doesnt like the 03 number format?

**Comment by Mr-Fen** [comment]
>>> avconv -r10 -i /home/pi/animation/frame%Nd.jpg -qscale2 /home/pi/animation/animation.mp4
Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    avconv -r10 -i /home/pi/animation/frame%Nd.jpg -qscale2 /home/pi/animation/animation.mp4
NameError: name 'avconv' is not defined
>>>

**Comment by Mr-Fen** [comment]
i am using Python 3.4.2 Shell on Raspberry Pi 3B

**Comment by waveform80** [comment]
I'm afraid that command isn't to be run from within Python. Just above that part, you'll find "1. To generate the video, begin by returning to the terminal window". In other words, this command is to be run directly in the terminal window *outside Python*. The prompt at which you type the command should look something like `pi@raspberrypi:~$` rather than the python prompt which is `>>>`

**Comment by Mr-Fen** [comment]
pi@raspberrypiB3:~ $ avconv -r 10 -i /home/pi/animation/frame%Nd.jpg -qscale 2 animation.mp4
bash: avconv: command not found
pi@raspberrypiB3:~ $

**Comment by waveform80** [comment]
You probably need to install libav-tools (`sudo apt-get install libav-tools`); I think it's listed under the [requirements page](https://www.raspberrypi.org/learning/push-button-stop-motion/requirements/) which should have a link to detailed instructions.

**Comment by Mr-Fen** [comment]
amazing what I miss when reading carefully and following detailed instructions :)
I thought i had installed all required libraries

thanks for the quick response and I hope this was the 'right' way to use github

**Comment by Mr-Fen** [comment]
the video has now complied, but the 'play' command doesnt play anything?

pi@raspberrypiB3:~ $ omxplayer animation.mp4
Video codec omx-h264 width 1920 height 1080 profile 100 fps 10.000000
Subtitle count: 0, state: off, index: 1, delay: 0

**Comment by waveform80** [comment]
No prob! And sure, it's a fine way to use github issues (which are also great for suggestions and enhancements as well as problems). The only thing I'd suggest for any future tickets is to have a quick look at [GitHub's markdown guide](https://guides.github.com/features/mastering-markdown/). The most important bit in there is how to include code clips (usually I find the triple-back-tick method the most flexible). It really doesn't matter for little snippets like in this ticket, but for more substantial chunks of code it's really useful to be able to include a nice syntax-highlighted chunk of Python without any effort:

```python
import foo
from bar import baz

def quux(a, b):
    return a + b
```

Or for that matter longer chunks of bash (the language used in the terminal):

```bash
pi@raspberrypi:~$ for dir in foo bar baz
> do
> avconv -r 10 -i /home/pi/$dir/frame%Nd.jpg -qscale 2 $dir/animation.mp4
> done
```

Also means when you paste in chunks of Python command line it gets treated as Python rather than a bunch of nested quotes (as in the first message), i.e.:

>>> import this

Versus:

```python
>>> import this
```

**Comment by waveform80** [comment]
> the video has now complied, but the 'play' command doesnt play anything?

Hmmm, that's bizarre - that ought to work (assuming avconv didn't produce any errors). I'll have a look a bit later tonight when I can put together an equivalent setup.

**Comment by PaulBrownMagic** [comment]
I'm having a similar issue. Ran `avconv -r 10 -i animation/frame%03d.jpg -qscale 2 -y output.mp4` and many other variations including setting `-f image2` and specifying the vcodec to use. All to no avail. 

No matter the command given, avconv is creating a very short video of black screen and then only the first frame is displayed. I can view the output by using VLC, however omxplayer just returns the message Mr-Fen described.

**Comment by waveform80** [comment]
> No matter the command given, avconv is creating a very short video of black screen and then only the first frame is displayed. I can view the output by using VLC, however omxplayer just returns the message Mr-Fen described.

Just to check (sorry if this is patronizing): when you say you can play it with VLC but not omxplayer, you're not attempting omxplayer over a remote link and expecting it to work (omxplayer's only useful locally on the Pi with a directly attached display, i.e. HDMI or composite out).

**Comment by Mr-Fen** [comment]
hi all,
I rebooted my Pi and reran the script with the same effect.  I have found that you need to have a lot of photos (like 20+) for it to actually work.

**Comment by PaulBrownMagic** [comment]
I was running omxplayer locally and viewing via HDMI. My test-case is 30 images long, so generates 3 seconds but it's all black followed by the single first frame.

**Comment by lawsie** [comment]
Looks like we need to do a bit of testing here. I'll add it to our list.

**Comment by MarcScott** [comment]
Had no luck playing mp4 file with omxplayer either.
I've changed the instructions to generate an h264 file, which seems to work
